### ISSUE TITLE
Junk in the cargo package source

### ISSUE THREAD

**Issue by bluss** [meh/rust-lzma#1]
lzma 0.2.0 has a 2.8 MB perf.data file in the cargo source, among other files.

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by meh** [comment]
Thanks, and luckily it wasn't on another of my repos that has 400M of `perf.data`

**Comment by bluss** [comment]
At some point cargo will deny the upload — that's how I realized in my repo. Thanks for fixing!
